name = "masque-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
http = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
dashmap = "5.5"
rlimit = "0.10"

# QUIC, HTTP/3 与 TLS 生态
quinn = "0.11"
rustls = { version = "0.23", features = ["ring"] }
rustls-pki-types = "1.4"
h3 = "0.0.8"
h3-quinn = "0.0.10"

# 证书加载与生成
rcgen = "0.13"
rustls-pemfile = "2.1" # 从磁盘读取证书
